# Generated by Django 4.2.7 on 2023-11-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='deskripsi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
