# Generated by Django 4.2.7 on 2023-11-17 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_berita_kategoriid_berita_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='beritaupdate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255, null=True)),
                ('isi', models.CharField(max_length=9999)),
                ('kategoriID', models.IntegerField(max_length=255, null=True)),
                ('gambar', models.ImageField(upload_to='media')),
                ('penulis', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], max_length=200, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categories')),
            ],
        ),
    ]
