# Generated by Django 4.2.7 on 2023-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritaupdate1',
            name='kategoriID',
            field=models.IntegerField(null=True),
        ),
    ]
